### ISSUE TITLE
Move this app to StarcounterApps?

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/CompositionProvider#8]
@tomalec WDYT about moving this app to https://github.com/StarcounterApps? This is where we have the Website app. In my opinion this would be a nice distinction:

- https://github.com/StarcounterApps - has the actual prefab apps that run on Starcounter platform
- https://github.com/Starcounter - has the platform, infrastructure, tooling

**Comment by Mackiovello** [comment]
I agree that the CompositionEditor should be moved. CompositionProvider should instead be [included in Starcounter](https://github.com/Starcounter/level1/issues/4019). Should it still be moved to the StarcounterApps repo?

**Comment by warpech** [comment]
The fact that CompositionProvider should be treated as a system app, does not defy that it is still an app. Therefore, I think it belongs in https://github.com/StarcounterApps.

**Comment by tomalec** [comment]
I agree with you both :)

**Comment by Mackiovello** [comment]
Great, let's do it

**Comment by warpech** [comment]
Moved this app to https://github.com/StarcounterApps/CompositionProvider
